apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: dockerhub.richrelevance.com/app
      context: ../../app
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
