apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: algo_ns
type: Opaque
data:
  secret: TVdFME4yUmlNR0ZtTlRNd05tVTRaR1JrWmpNeE1UQXhOMlF5WkdJeE5qazJaalJrWXpCa1pqTTJOR1V3WWpreE16azJZV1ZtTUdWa01UVXlaV1JqTW1FNE5EaGxZamd4TVROaE9EZ3hPVGcyTWpsa05qTXpNR000Wm1FNE5ERmlPVFJrTWc9PQ==
